Update infrastructure and reference container

diff --git a/.github/workflows/corevalidation.yml b/.github/workflows/corevalidation.yml
--- a/.github/workflows/corevalidation.yml
+++ b/.github/workflows/corevalidation.yml
@@ -77,17 +77,6 @@ jobs:
           . <(curl https://aka.ms/vcpkg-init.sh -L)
           vcpkg x-update-registry --all
           vcpkg activate
-          
-          echo "Fix library search path for VHT models"
-          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(dirname $(which VHT_MPS2_Cortex-M3))" >> $GITHUB_ENV
-
-          echo "Fix execute permissions for VHT models"
-          chmod +x $(dirname $(which VHT_MPS2_Cortex-M3))/VHT_*
-
-          echo "Patch CMSIS-Toolbox"
-          pushd $(dirname $(which cbuild))/../etc
-          curl -O https://raw.githubusercontent.com/Open-CMSIS-Pack/devtools/main/tools/buildmgr/cbuildgen/config/CLANG.17.0.1.cmake
-          popd
 
       - name: Activate Arm tool license
         working-directory: ./CMSIS/CoreValidation/Project
@@ -120,7 +109,7 @@ jobs:
           cpackget add /home/runner/Cortex_DFP/ARM.Cortex_DFP.pdsc
 
           echo "Build test projects ..."
-          ./build.py --verbose -m VHT -c ${{ matrix.compiler }} build || echo "::warning::=== Some configurations failed to build! ==="
+          ./build.py --verbose -m FVP -c ${{ matrix.compiler }} build || echo "::warning::=== Some configurations failed to build! ==="
 
       - name: Perform CodeQL Analysis
         if: ${{ !cancelled() && matrix.compiler == 'GCC' }}
@@ -134,7 +123,7 @@ jobs:
           vcpkg activate
       
           echo "Run test projects ..."
-          ./build.py --verbose -m VHT -c ${{ matrix.compiler }} -d "CM[047]*" -d "CM3" -d "CM[23]3*" run || echo "::warning::==== Some configurations failed to run! ==="
+          ./build.py --verbose -m FVP -c ${{ matrix.compiler }} -d "CM[047]*" -d "CM3" -d "CM[23]3*" run || echo "::warning::==== Some configurations failed to run! ==="
 
       - name: Deactivate Arm tool license
         if: always()
